"""Reusable ML training pipeline for signal models."""

from .pipeline import (
    FEATURE_COLUMNS,
    FEATURE_SET_VERSION,
    FEATURE_IMPORTANCES_FILE_NAME,
    MANIFEST_FILE_NAME,
    METRICS_FILE_NAME,
    MODEL_FILE_NAME,
    GateResult,
    MLDataSet,
    MLDataSplit,
    MLEnvironmentDiagnostics,
    MLTrainingRun,
    PipelineError,
    apply_quality_gate,
    assert_environment_ready,
    build_dataset,
    build_feature_frame,
    build_manifest,
    create_model_id,
    diagnose_environment,
    evaluate_model,
    generate_labels,
    get_source_commit,
    run_signal_training_pipeline,
    save_model_artifacts,
    split_dataset,
    train_xgboost_classifier,
)

