from __future__ import annotations

import argparse
import importlib
import json
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, Optional

ROOT = Path(__file__).resolve().parents[1]
root_str = str(ROOT)
if root_str not in sys.path:
    sys.path.insert(0, root_str)


DEFAULT_CLOB_URL = "https://clob.polymarket.com"
DEFAULT_RELAYER_URL = "https://relayer-v2.polymarket.com"
DEFAULT_CHAIN_ID = 137
DEFAULT_SECRET_OUTPUT = Path("secrets/polymarket_clob.env")


class SetupError(RuntimeError):
    pass


def _clean_key(raw: str) -> str:
    return str(raw or "").strip().strip('"').strip("'")


def mask_secret(value: Any, *, keep: int = 4) -> str:
    text = str(value or "")
    if not text:
        return ""
    if len(text) <= keep * 2:
        return "*" * len(text)
    return f"{text[:keep]}...{text[-keep:]}"


def parse_key_value_file(path: Path) -> Dict[str, str]:
    values: Dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        item = line.strip()
        if not item or item.startswith("#"):
            continue
        if item.lower().startswith("export "):
            item = item[7:].strip()
        sep = "=" if "=" in item else ":" if ":" in item else ""
        if not sep:
            continue
        key, value = item.split(sep, 1)
        key = key.strip()
        value_clean = _clean_key(value)
        if re.fullmatch(r"[A-Z_][A-Z0-9_]*", key):
            values[key] = value_clean
        elif key == "address" and re.fullmatch(r"0x[a-fA-F0-9]{40}", value_clean):
            values.setdefault("RELAYER_API_KEY_ADDRESS", value_clean)
        elif key == "key" and len(value_clean) >= 20:
            values.setdefault("RELAYER_API_KEY", value_clean)
    return values


def load_env_files(paths: Iterable[Path]) -> Dict[str, str]:
    loaded: Dict[str, str] = {}
    for path in paths:
        for key, value in parse_key_value_file(path).items():
            if key not in os.environ:
                os.environ[key] = value
            loaded[key] = value
    return loaded


def require_env(name: str) -> str:
    value = _clean_key(os.getenv(name, ""))
    if not value:
        raise SetupError(f"missing required environment variable: {name}")
    return value


def optional_env(name: str, default: str = "") -> str:
    return _clean_key(os.getenv(name, default))


def normalize_private_key(value: str) -> str:
    private_key = _clean_key(value)
    if private_key and not private_key.startswith("0x"):
        private_key = f"0x{private_key}"
    if not re.fullmatch(r"0x[a-fA-F0-9]{64}", private_key or ""):
        raise SetupError("PRIVATE_KEY must be a 0x-prefixed 32-byte hex string")
    return private_key


def import_required(module_name: str, install_hint: str) -> Any:
    try:
        return importlib.import_module(module_name)
    except ImportError as exc:
        raise SetupError(f"missing package {module_name}; install with: {install_hint}") from exc


def get_owner_address(private_key: str) -> str:
    eth_account = import_required("eth_account", "pip install eth-account")
    account = eth_account.Account.from_key(private_key)
    return str(account.address)


def normalize_api_creds(raw: Any) -> Dict[str, str]:
    if raw is None:
        return {}
    if isinstance(raw, dict):
        src = raw
    else:
        src = {
            "apiKey": getattr(raw, "apiKey", None) or getattr(raw, "api_key", None) or getattr(raw, "key", None),
            "secret": getattr(raw, "secret", None) or getattr(raw, "api_secret", None),
            "passphrase": getattr(raw, "passphrase", None) or getattr(raw, "api_passphrase", None),
        }
    return {
        "CLOB_API_KEY": _clean_key(src.get("apiKey") or src.get("api_key") or src.get("key") or ""),
        "CLOB_SECRET": _clean_key(src.get("secret") or src.get("api_secret") or ""),
        "CLOB_PASS_PHRASE": _clean_key(src.get("passphrase") or src.get("api_passphrase") or ""),
    }


def write_env_file(path: Path, values: Dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    existing = parse_key_value_file(path)
    existing.update({k: v for k, v in values.items() if v})
    lines = [
        "# Polymarket live CLOB credentials. Do not commit this file.",
        "# Generated by scripts/polymarket_clob_setup.py",
    ]
    for key in sorted(existing):
        lines.append(f"{key}={existing[key]}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def print_json(data: Dict[str, Any]) -> None:
    print(json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True))


def build_clob_client_for_l1(private_key: str) -> Any:
    clob = import_required("py_clob_client_v2", "pip install py-clob-client-v2")
    return clob.ClobClient(
        host=optional_env("CLOB_API_URL", DEFAULT_CLOB_URL),
        chain_id=int(optional_env("CHAIN_ID", str(DEFAULT_CHAIN_ID))),
        key=private_key,
    )


def build_api_creds() -> Any:
    clob = import_required("py_clob_client_v2", "pip install py-clob-client-v2")
    return clob.ApiCreds(
        api_key=require_env("CLOB_API_KEY"),
        api_secret=require_env("CLOB_SECRET"),
        api_passphrase=require_env("CLOB_PASS_PHRASE"),
    )


def build_clob_client_for_deposit_wallet(private_key: str) -> Any:
    clob = import_required("py_clob_client_v2", "pip install py-clob-client-v2")
    signature_type = getattr(getattr(clob, "SignatureTypeV2", object), "POLY_1271", 3)
    return clob.ClobClient(
        host=optional_env("CLOB_API_URL", DEFAULT_CLOB_URL),
        chain_id=int(optional_env("CHAIN_ID", str(DEFAULT_CHAIN_ID))),
        key=private_key,
        creds=build_api_creds(),
        signature_type=signature_type,
        funder=require_env("DEPOSIT_WALLET_ADDRESS"),
    )


def create_or_derive_clob_creds(args: argparse.Namespace) -> None:
    private_key = normalize_private_key(require_env("PRIVATE_KEY"))
    owner_address = get_owner_address(private_key)
    client = build_clob_client_for_l1(private_key)
    creds = normalize_api_creds(client.create_or_derive_api_key())
    if not all(creds.values()):
        raise SetupError(f"SDK returned incomplete credentials: {sorted(k for k, v in creds.items() if not v)}")
    if args.write_env:
        values = dict(creds)
        values.update(
            {
                "CLOB_API_URL": optional_env("CLOB_API_URL", DEFAULT_CLOB_URL),
                "CHAIN_ID": optional_env("CHAIN_ID", str(DEFAULT_CHAIN_ID)),
                "POLY_SIGNER_ADDRESS": owner_address,
            }
        )
        write_env_file(Path(args.write_env), values)
    output_creds = creds if args.print_secret else {k: mask_secret(v) for k, v in creds.items()}
    print_json(
        {
            "ok": True,
            "owner_address": owner_address,
            "credentials": output_creds,
            "secret_output": str(args.write_env) if args.write_env else "",
            "printed_full_secret": bool(args.print_secret),
        }
    )


def build_relayer_client(private_key: str) -> Any:
    relayer_mod = import_required("py_builder_relayer_client.client", "pip install py-builder-relayer-client")
    signing_cfg = import_required("py_builder_signing_sdk.config", "pip install py-builder-relayer-client")
    builder_config = signing_cfg.BuilderConfig(
        local_builder_creds=signing_cfg.BuilderApiKeyCreds(
            key=require_env("BUILDER_API_KEY"),
            secret=require_env("BUILDER_SECRET"),
            passphrase=require_env("BUILDER_PASS_PHRASE"),
        )
    )
    return relayer_mod.RelayClient(
        optional_env("RELAYER_URL", DEFAULT_RELAYER_URL),
        int(optional_env("CHAIN_ID", str(DEFAULT_CHAIN_ID))),
        private_key,
        builder_config,
    )


def derive_deposit_wallet(args: argparse.Namespace) -> None:
    private_key = normalize_private_key(require_env("PRIVATE_KEY"))
    relayer = build_relayer_client(private_key)
    wallet = str(relayer.get_expected_safe())
    if args.write_env:
        write_env_file(Path(args.write_env), {"DEPOSIT_WALLET_ADDRESS": wallet})
    print_json({"ok": True, "deposit_wallet_address": wallet, "secret_output": str(args.write_env) if args.write_env else ""})


def deploy_deposit_wallet(args: argparse.Namespace) -> None:
    if not args.yes:
        raise SetupError("deployment is live; rerun with --yes after confirming jurisdiction, wallet, and relayer credentials")
    private_key = normalize_private_key(require_env("PRIVATE_KEY"))
    relayer = build_relayer_client(private_key)
    wallet = str(relayer.get_expected_safe())
    response = relayer.deploy()
    wait_result = response.wait() if args.wait else None
    if args.write_env:
        write_env_file(Path(args.write_env), {"DEPOSIT_WALLET_ADDRESS": wallet})
    print_json(
        {
            "ok": True,
            "deposit_wallet_address": wallet,
            "submitted": str(response),
            "confirmed": str(wait_result) if wait_result is not None else "",
            "secret_output": str(args.write_env) if args.write_env else "",
        }
    )


def sync_balance_allowance(args: argparse.Namespace) -> None:
    private_key = normalize_private_key(require_env("PRIVATE_KEY"))
    clob = import_required("py_clob_client_v2", "pip install py-clob-client-v2")
    client = build_clob_client_for_deposit_wallet(private_key)
    asset_type = getattr(getattr(clob, "AssetType", object), args.asset_type)
    signature_type = getattr(getattr(clob, "SignatureTypeV2", object), "POLY_1271", 3)
    if hasattr(signature_type, "value"):
        signature_type = signature_type.value
    params_cls = getattr(clob, "BalanceAllowanceParams")
    kwargs = {"asset_type": asset_type, "signature_type": signature_type}
    if args.token_id:
        kwargs["token_id"] = args.token_id
    result = client.update_balance_allowance(params_cls(**kwargs))
    print_json({"ok": True, "asset_type": args.asset_type, "token_id": args.token_id or "", "result": result})


def get_server_time() -> Optional[Any]:
    try:
        import requests

        resp = requests.get(f"{optional_env('CLOB_API_URL', DEFAULT_CLOB_URL)}/time", timeout=8)
        resp.raise_for_status()
        return resp.json()
    except Exception as exc:
        return {"error": str(exc)}


def check_relayer_auth(args: argparse.Namespace) -> None:
    requests = import_required("requests", "pip install requests")
    relayer_url = optional_env("RELAYER_URL", DEFAULT_RELAYER_URL).rstrip("/")
    address = require_env("RELAYER_API_KEY_ADDRESS")
    headers = {
        "RELAYER_API_KEY": require_env("RELAYER_API_KEY"),
        "RELAYER_API_KEY_ADDRESS": address,
    }

    tx_resp = requests.get(f"{relayer_url}/transactions", headers=headers, timeout=15)
    deployed_resp = requests.get(f"{relayer_url}/deployed", params={"address": address}, headers=headers, timeout=15)
    tx_payload: Any
    try:
        tx_payload = tx_resp.json()
    except Exception:
        tx_payload = None
    deployed_payload: Any
    try:
        deployed_payload = deployed_resp.json()
    except Exception:
        deployed_payload = None
    print_json(
        {
            "ok": bool(tx_resp.ok and deployed_resp.ok),
            "transactions_status_code": tx_resp.status_code,
            "transactions_count": len(tx_payload) if isinstance(tx_payload, list) else None,
            "transaction_states": sorted({str(item.get("state")) for item in tx_payload if isinstance(item, dict)})[:10]
            if isinstance(tx_payload, list)
            else [],
            "deployed_status_code": deployed_resp.status_code,
            "address_deployed": deployed_payload.get("deployed") if isinstance(deployed_payload, dict) else None,
        }
    )


def doctor(args: argparse.Namespace) -> None:
    loaded_keys = sorted(load_env_files([Path(p) for p in args.env_file]))
    private_key = optional_env("PRIVATE_KEY")
    owner_address = ""
    private_key_valid = False
    if private_key:
        try:
            normalized = normalize_private_key(private_key)
            owner_address = get_owner_address(normalized)
            private_key_valid = True
        except Exception as exc:
            owner_address = f"error: {exc}"
    checks = {
        "env_files_loaded_keys": loaded_keys,
        "py_clob_client_v2": importlib.util.find_spec("py_clob_client_v2") is not None,
        "py_builder_relayer_client": importlib.util.find_spec("py_builder_relayer_client") is not None,
        "private_key_present": bool(private_key),
        "private_key_valid": private_key_valid,
        "owner_address": owner_address,
        "clob_api_creds_present": all(optional_env(k) for k in ("CLOB_API_KEY", "CLOB_SECRET", "CLOB_PASS_PHRASE")),
        "deposit_wallet_address_present": bool(optional_env("DEPOSIT_WALLET_ADDRESS")),
        "builder_creds_present": all(optional_env(k) for k in ("BUILDER_API_KEY", "BUILDER_SECRET", "BUILDER_PASS_PHRASE")),
        "relayer_api_key_present": bool(optional_env("RELAYER_API_KEY")),
        "relayer_api_key_address_present": bool(optional_env("RELAYER_API_KEY_ADDRESS")),
        "server_time": get_server_time(),
    }
    print_json({"ok": True, "checks": checks})


def add_common_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--env-file",
        action="append",
        default=[],
        help="Load KEY=value or KEY: value secrets before running. Can be repeated.",
    )


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Prepare local Polymarket CLOB live credentials without placing orders.")
    sub = parser.add_subparsers(dest="command", required=True)

    doctor_p = sub.add_parser("doctor", help="Check local packages and required environment variables.")
    add_common_args(doctor_p)
    doctor_p.set_defaults(func=doctor)

    relayer_p = sub.add_parser("check-relayer-auth", help="Verify relayer auth with read-only endpoints.")
    add_common_args(relayer_p)
    relayer_p.set_defaults(func=check_relayer_auth)

    creds_p = sub.add_parser("derive-clob-creds", help="Create or derive CLOB L2 credentials from PRIVATE_KEY.")
    add_common_args(creds_p)
    creds_p.add_argument("--write-env", default=str(DEFAULT_SECRET_OUTPUT), help="Write full credentials to an ignored env file.")
    creds_p.add_argument("--print-secret", action="store_true", help="Print full secret values to stdout. Avoid unless necessary.")
    creds_p.set_defaults(func=create_or_derive_clob_creds)

    wallet_p = sub.add_parser("derive-deposit-wallet", help="Derive the expected POLY_1271 deposit wallet address.")
    add_common_args(wallet_p)
    wallet_p.add_argument("--write-env", default=str(DEFAULT_SECRET_OUTPUT), help="Write the wallet address to an ignored env file.")
    wallet_p.set_defaults(func=derive_deposit_wallet)

    deploy_p = sub.add_parser("deploy-deposit-wallet", help="Submit a live relayer wallet deployment transaction.")
    add_common_args(deploy_p)
    deploy_p.add_argument("--write-env", default=str(DEFAULT_SECRET_OUTPUT), help="Write the wallet address to an ignored env file.")
    deploy_p.add_argument("--wait", action="store_true", help="Wait for the relayer confirmation.")
    deploy_p.add_argument("--yes", action="store_true", help="Required guardrail for live relayer submission.")
    deploy_p.set_defaults(func=deploy_deposit_wallet)

    sync_p = sub.add_parser("sync-balance-allowance", help="Sync CLOB balance/allowance cache for the deposit wallet.")
    add_common_args(sync_p)
    sync_p.add_argument("--asset-type", choices=["COLLATERAL", "CONDITIONAL"], default="COLLATERAL")
    sync_p.add_argument("--token-id", default="", help="Required by Polymarket for CONDITIONAL token cache updates.")
    sync_p.set_defaults(func=sync_balance_allowance)

    args = parser.parse_args(argv)
    load_env_files([Path(p) for p in getattr(args, "env_file", [])])
    try:
        args.func(args)
        return 0
    except SetupError as exc:
        print_json({"ok": False, "error": str(exc)})
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
